name: deploy-book

on:
  push:
    branches:
    - pelmeni

  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Setup uv
      uses: yezz123/setup-uv@v4
      with:
        uv-venv: venv

    - name: Install dependencies
      run: |
        uv pip install -r Lab1/requirements.txt

    - name: Build the book
      run: |
        jupyter-book build Lab1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "Lab1/_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2